// Code generated by hand to mirror what controller-gen would produce.
// Re-run controller-gen when types.go changes; we keep this in tree so
// `go build` works without the codegen toolchain installed.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// --- BrowserSession ------------------------------------------------------

// DeepCopyInto copies the receiver into out.
func (in *BrowserSession) DeepCopyInto(out *BrowserSession) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of in.
func (in *BrowserSession) DeepCopy() *BrowserSession {
	if in == nil {
		return nil
	}
	out := new(BrowserSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy.
func (in *BrowserSession) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for spec is just *out = *in (no pointers).
func (in *BrowserSessionSpec) DeepCopyInto(out *BrowserSessionSpec) {
	*out = *in
}

func (in *BrowserSessionStatus) DeepCopyInto(out *BrowserSessionStatus) {
	*out = *in
	if in.Connection != nil {
		out.Connection = new(SessionConnection)
		*out.Connection = *in.Connection
	}
	if in.LastActivityAt != nil {
		out.LastActivityAt = in.LastActivityAt.DeepCopy()
	}
	if in.StartedAt != nil {
		out.StartedAt = in.StartedAt.DeepCopy()
	}
	if in.EndedAt != nil {
		out.EndedAt = in.EndedAt.DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// --- BrowserSessionList --------------------------------------------------

func (in *BrowserSessionList) DeepCopyInto(out *BrowserSessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]BrowserSession, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *BrowserSessionList) DeepCopy() *BrowserSessionList {
	if in == nil {
		return nil
	}
	out := new(BrowserSessionList)
	in.DeepCopyInto(out)
	return out
}

func (in *BrowserSessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- BrowserSessionPool --------------------------------------------------

func (in *BrowserSessionPool) DeepCopyInto(out *BrowserSessionPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *BrowserSessionPool) DeepCopy() *BrowserSessionPool {
	if in == nil {
		return nil
	}
	out := new(BrowserSessionPool)
	in.DeepCopyInto(out)
	return out
}

func (in *BrowserSessionPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BrowserSessionPoolSpec) DeepCopyInto(out *BrowserSessionPoolSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

func (in *BrowserSessionPoolStatus) DeepCopyInto(out *BrowserSessionPoolStatus) {
	*out = *in
	if in.LastReplenishedAt != nil {
		out.LastReplenishedAt = in.LastReplenishedAt.DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// --- BrowserSessionPoolList ----------------------------------------------

func (in *BrowserSessionPoolList) DeepCopyInto(out *BrowserSessionPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]BrowserSessionPool, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *BrowserSessionPoolList) DeepCopy() *BrowserSessionPoolList {
	if in == nil {
		return nil
	}
	out := new(BrowserSessionPoolList)
	in.DeepCopyInto(out)
	return out
}

func (in *BrowserSessionPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
